apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "mybackend.fullname" . }}-secret
  labels:
    {{- include "mybackend.labels" . | nindent 4 }}
data:
  admin: {{ .Values.ingress.clientSecret | b64enc | quote }}